stages:
  - code style
  - static analysis
  - tests

Code sniffer:
  stage: code style
  image: php8.0-extra
  script:
    - composer install
    - composer phpcs
  cache:
    key: $CI_COMMIT_SHORT_SHA
    paths:
      - vendor

PHP Stan:
  stage: static analysis
  image: php8.0-extra
  script:
    - composer install
    - composer phpstan
  cache:
    key: $CI_COMMIT_SHORT_SHA
    paths:
      - vendor

Unit tests:
  stage: tests
  image: php8.0-extra
  script:
    - composer install
    - composer unit-tests
  cache:
    key: $CI_COMMIT_SHORT_SHA
    paths:
      - vendor
