stages:
  - code style
  - tests

Code sniffer:
  stage: code style
  image: php7.4-extra
  script:
    - composer install
    - composer phpcs
  cache:
    key: $CI_COMMIT_SHORT_SHA
    paths:
      - vendor

Unit tests:
  stage: tests
  image: php7.4-extra
  script:
    - composer install
    - composer tests-unit
  cache:
    key: $CI_COMMIT_SHORT_SHA
    paths:
      - vendor
