version: '3.9'
services:
  app:
    container_name: cli-texy-converter
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 7.4
    volumes:
      - .:/var/www/html
    stdin_open: true
    tty: true
